#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = %cd%

CC = gcc.exe
CXX = g++.exe
AR = ar.exe
LD = g++.exe
WINDRES = windres.exe

INC = 
CFLAGS = -Wall -fexceptions
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = 

INC_DEBUG = $(INC) -Iinclude
CFLAGS_DEBUG = $(CFLAGS) -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj\\Debug
DEP_DEBUG = 
OUT_DEBUG = bin\\Debug\\BrainCubeInterpreter.exe

INC_RELEASE = $(INC) -Iinclude
CFLAGS_RELEASE = $(CFLAGS) -O2
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj\\Release
DEP_RELEASE = 
OUT_RELEASE = bin\\Release\\BrainCubeInterpreter.exe

OBJ_DEBUG = $(OBJDIR_DEBUG)\\main.o $(OBJDIR_DEBUG)\\src\\Stmt_SysCmd.o $(OBJDIR_DEBUG)\\src\\Stmt_PtrCmd.o $(OBJDIR_DEBUG)\\src\\Stmt_Declare.o $(OBJDIR_DEBUG)\\src\\Expression.o $(OBJDIR_DEBUG)\\src\\Ctrl_While.o $(OBJDIR_DEBUG)\\src\\Ctrl_Repeat.o $(OBJDIR_DEBUG)\\src\\Ctrl_Main.o $(OBJDIR_DEBUG)\\src\\Ctrl_If.o $(OBJDIR_DEBUG)\\src\\Ctrl.o $(OBJDIR_DEBUG)\\src\\CellPointer.o $(OBJDIR_DEBUG)\\src\\Cell.o

OBJ_RELEASE = $(OBJDIR_RELEASE)\\main.o $(OBJDIR_RELEASE)\\src\\Stmt_SysCmd.o $(OBJDIR_RELEASE)\\src\\Stmt_PtrCmd.o $(OBJDIR_RELEASE)\\src\\Stmt_Declare.o $(OBJDIR_RELEASE)\\src\\Expression.o $(OBJDIR_RELEASE)\\src\\Ctrl_While.o $(OBJDIR_RELEASE)\\src\\Ctrl_Repeat.o $(OBJDIR_RELEASE)\\src\\Ctrl_Main.o $(OBJDIR_RELEASE)\\src\\Ctrl_If.o $(OBJDIR_RELEASE)\\src\\Ctrl.o $(OBJDIR_RELEASE)\\src\\CellPointer.o $(OBJDIR_RELEASE)\\src\\Cell.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	cmd /c if not exist bin\\Debug md bin\\Debug
	cmd /c if not exist $(OBJDIR_DEBUG) md $(OBJDIR_DEBUG)
	cmd /c if not exist $(OBJDIR_DEBUG)\\src md $(OBJDIR_DEBUG)\\src

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)\\main.o: main.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c main.cpp -o $(OBJDIR_DEBUG)\\main.o

$(OBJDIR_DEBUG)\\src\\Stmt_SysCmd.o: src\\Stmt_SysCmd.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\Stmt_SysCmd.cpp -o $(OBJDIR_DEBUG)\\src\\Stmt_SysCmd.o

$(OBJDIR_DEBUG)\\src\\Stmt_PtrCmd.o: src\\Stmt_PtrCmd.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\Stmt_PtrCmd.cpp -o $(OBJDIR_DEBUG)\\src\\Stmt_PtrCmd.o

$(OBJDIR_DEBUG)\\src\\Stmt_Declare.o: src\\Stmt_Declare.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\Stmt_Declare.cpp -o $(OBJDIR_DEBUG)\\src\\Stmt_Declare.o

$(OBJDIR_DEBUG)\\src\\Expression.o: src\\Expression.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\Expression.cpp -o $(OBJDIR_DEBUG)\\src\\Expression.o

$(OBJDIR_DEBUG)\\src\\Ctrl_While.o: src\\Ctrl_While.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\Ctrl_While.cpp -o $(OBJDIR_DEBUG)\\src\\Ctrl_While.o

$(OBJDIR_DEBUG)\\src\\Ctrl_Repeat.o: src\\Ctrl_Repeat.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\Ctrl_Repeat.cpp -o $(OBJDIR_DEBUG)\\src\\Ctrl_Repeat.o

$(OBJDIR_DEBUG)\\src\\Ctrl_Main.o: src\\Ctrl_Main.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\Ctrl_Main.cpp -o $(OBJDIR_DEBUG)\\src\\Ctrl_Main.o

$(OBJDIR_DEBUG)\\src\\Ctrl_If.o: src\\Ctrl_If.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\Ctrl_If.cpp -o $(OBJDIR_DEBUG)\\src\\Ctrl_If.o

$(OBJDIR_DEBUG)\\src\\Ctrl.o: src\\Ctrl.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\Ctrl.cpp -o $(OBJDIR_DEBUG)\\src\\Ctrl.o

$(OBJDIR_DEBUG)\\src\\CellPointer.o: src\\CellPointer.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\CellPointer.cpp -o $(OBJDIR_DEBUG)\\src\\CellPointer.o

$(OBJDIR_DEBUG)\\src\\Cell.o: src\\Cell.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src\\Cell.cpp -o $(OBJDIR_DEBUG)\\src\\Cell.o

clean_debug: 
	cmd /c del /f $(OBJ_DEBUG) $(OUT_DEBUG)
	cmd /c rd bin\\Debug
	cmd /c rd $(OBJDIR_DEBUG)
	cmd /c rd $(OBJDIR_DEBUG)\\src

before_release: 
	cmd /c if not exist bin\\Release md bin\\Release
	cmd /c if not exist $(OBJDIR_RELEASE) md $(OBJDIR_RELEASE)
	cmd /c if not exist $(OBJDIR_RELEASE)\\src md $(OBJDIR_RELEASE)\\src

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)\\main.o: main.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c main.cpp -o $(OBJDIR_RELEASE)\\main.o

$(OBJDIR_RELEASE)\\src\\Stmt_SysCmd.o: src\\Stmt_SysCmd.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\Stmt_SysCmd.cpp -o $(OBJDIR_RELEASE)\\src\\Stmt_SysCmd.o

$(OBJDIR_RELEASE)\\src\\Stmt_PtrCmd.o: src\\Stmt_PtrCmd.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\Stmt_PtrCmd.cpp -o $(OBJDIR_RELEASE)\\src\\Stmt_PtrCmd.o

$(OBJDIR_RELEASE)\\src\\Stmt_Declare.o: src\\Stmt_Declare.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\Stmt_Declare.cpp -o $(OBJDIR_RELEASE)\\src\\Stmt_Declare.o

$(OBJDIR_RELEASE)\\src\\Expression.o: src\\Expression.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\Expression.cpp -o $(OBJDIR_RELEASE)\\src\\Expression.o

$(OBJDIR_RELEASE)\\src\\Ctrl_While.o: src\\Ctrl_While.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\Ctrl_While.cpp -o $(OBJDIR_RELEASE)\\src\\Ctrl_While.o

$(OBJDIR_RELEASE)\\src\\Ctrl_Repeat.o: src\\Ctrl_Repeat.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\Ctrl_Repeat.cpp -o $(OBJDIR_RELEASE)\\src\\Ctrl_Repeat.o

$(OBJDIR_RELEASE)\\src\\Ctrl_Main.o: src\\Ctrl_Main.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\Ctrl_Main.cpp -o $(OBJDIR_RELEASE)\\src\\Ctrl_Main.o

$(OBJDIR_RELEASE)\\src\\Ctrl_If.o: src\\Ctrl_If.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\Ctrl_If.cpp -o $(OBJDIR_RELEASE)\\src\\Ctrl_If.o

$(OBJDIR_RELEASE)\\src\\Ctrl.o: src\\Ctrl.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\Ctrl.cpp -o $(OBJDIR_RELEASE)\\src\\Ctrl.o

$(OBJDIR_RELEASE)\\src\\CellPointer.o: src\\CellPointer.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\CellPointer.cpp -o $(OBJDIR_RELEASE)\\src\\CellPointer.o

$(OBJDIR_RELEASE)\\src\\Cell.o: src\\Cell.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src\\Cell.cpp -o $(OBJDIR_RELEASE)\\src\\Cell.o

clean_release: 
	cmd /c del /f $(OBJ_RELEASE) $(OUT_RELEASE)
	cmd /c rd bin\\Release
	cmd /c rd $(OBJDIR_RELEASE)
	cmd /c rd $(OBJDIR_RELEASE)\\src

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

